apiVersion: v2
version: 1.2.1
appVersion: "1.11.0"
kubeVersion: ">=1.30.14-0"
name: newt
description: Helm chart to deploy Newt (fosrl/newt) client instance
type: application
keywords:
  - newt
  - pangolin
  - vpn
  - wireguard
  - networking
home: https://digpangolin.com/
icon: https://raw.githubusercontent.com/fosrl/pangolin/refs/heads/main/public/logo/pangolin_orange.svg
sources:
  - https://github.com/fosrl/helm-charts
  - https://github.com/fosrl/newt
maintainers:
  - name: marcschaeferger
    email: info@marcschaeferger.de
    url: https://github.com/marcschaeferger
annotations:
  artifacthub.io/category: networking
  artifacthub.io/changes: |
    - kind: changed
      description: "Bump Chart version to 1.2.1 and Chart AppVersion to Newt v1.11.0."
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: newt-dockerhub
      image: docker.io/fosrl/newt:1.11.0
      whitelisted: false
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    - name: newt-ghcr
      image: ghcr.io/fosrl/newt:1.11.0
      whitelisted: false
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: support
      url: https://github.com/fosrl/helm-charts/issues
    - name: documentation
      url: https://docs.digpangolin.com/self-host/manual/kubernetes
  artifacthub.io/prerelease: "false"
#  artifacthub.io/recommendations: |
#    - url: https://artifacthub.io/packages/helm/fosrl/pangolin
  artifacthub.io/signKey: |
    fingerprint: 48E7F670FCC13645FC48B08D587294B228C2EC2C
    url: https://charts.fossorial.io/pgp_keys.asc

# Other annotations for artifacthub.io:
# References:
#   - https://artifacthub.io/docs/topics/annotations/helm/
#
# artifacthub.io/crds: |
#   - kind: MyKind
#     version: v1
#     name: mykind
#     displayName: My Kind
#     description: Some nice description
# artifacthub.io/crdsExamples: |
#   - apiVersion: v1
#     kind: MyKind
#     metadata:
#       name: mykind
#     spec:
#       replicas: 1
# artifacthub.io/operator: "true"
# artifacthub.io/operatorCapabilities: Basic Install
#
#
# artifacthub.io/screenshots: |
#   - title: Newt
#     url: https://raw.githubusercontent.com/fosrl/pangolin/refs/heads/main/public/logo/pangolin_orange.svg
