apiVersion: v2
version: 0.1.0-alpha.1
appVersion: "1.18.3"
kubeVersion: ">=1.30.14-0"
name: pangolin
description: Pangolin Helm Chart
type: application
keywords:
  - pangolin
  - vpn
  - wireguard
  - networking
home: https://digpangolin.com/
icon: https://raw.githubusercontent.com/fosrl/pangolin/refs/heads/main/public/logo/pangolin_orange.svg
sources:
  - https://github.com/fosrl/helm-charts
  - https://github.com/fosrl/pangolin
maintainers:
  - name: marcschaeferger
    email: info@marcschaeferger.de
    url: https://github.com/marcschaeferger
dependencies:
  - name: cloudnative-pg
    alias: cnpg-operator
    version: 0.28.0
    repository: https://cloudnative-pg.github.io/charts
    condition: cnpg-operator.enabled
  - name: cluster
    alias: cnpg-cluster
    version: 0.6.0
    repository: https://cloudnative-pg.github.io/charts
    condition: cnpg-cluster.enabled
annotations:
  artifacthub.io/category: networking
  artifacthub.io/changes: |
    - kind: changed
      description: "Bump Chart version to 0.1.0-alpha.1 and Chart AppVersion to Pangolin v1.18.3."
  artifacthub.io/images: |
    - name: pangolin-dockerhub
      image: docker.io/fosrl/pangolin:1.18.3
      whitelisted: false
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    - name: pangolin-ghcr
      image: ghcr.io/fosrl/pangolin:1.18.3
      whitelisted: false
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    - name: pangolin-postgresql-dockerhub
      image: docker.io/fosrl/pangolin:postgresql-1.18.3
      whitelisted: false
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    - name: pangolin-postgresql-ghcr
      image: ghcr.io/fosrl/pangolin:postgresql-1.18.3
      whitelisted: false
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: support
      url: https://github.com/fosrl/helm-charts/issues
    - name: documentation
      url: https://docs.digpangolin.com/self-host/manual/kubernetes
  artifacthub.io/prerelease: "true"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/fosrl/newt
  artifacthub.io/signKey: |
    fingerprint: 48E7F670FCC13645FC48B08D587294B228C2EC2C
    url: https://charts.fossorial.io/pgp_keys.asc
  artifacthub.io/screenshots: |
    - title: Pangolin-UI
      url: https://github.com/fosrl/pangolin/raw/main/public/screenshots/hero.png

# Other annotations for artifacthub.io:
# References:
#   - https://artifacthub.io/docs/topics/annotations/helm/
#
# artifacthub.io/crds: |
#   - kind: MyKind
#     version: v1
#     name: mykind
#     displayName: My Kind
#     description: Some nice description
# artifacthub.io/crdsExamples: |
#   - apiVersion: v1
#     kind: MyKind
#     metadata:
#       name: mykind
#     spec:
#       replicas: 1
# artifacthub.io/operator: "true"
# artifacthub.io/operatorCapabilities: Basic Install
