{{- $mode := include "pangolin.db.mode" . -}}
{{- $db := default (dict) .Values.database -}}
{{- $conn := default (dict) (get $db "connection") -}}
{{- $cnpg := default (dict) (get $db "cloudnativepg") -}}
{{- $cnpgConn := default (dict) (get $cnpg "connection") -}}
{{- $cnpgGenerated := default (dict) (get $cnpgConn "generatedSecret") -}}
{{- if and (eq $mode "cloudnativepg") ((get $cnpgGenerated "create") | default false) (not (get $conn "existingSecretName")) (not (get $cnpgConn "existingSecretName")) }}
{{- $metaAnns := include "pangolin.global.commonAnnotations" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pangolin.database.connectionSecretName" . }}
  namespace: {{ include "pangolin.namespace" . }}
  labels:
    {{- include "pangolin.labels" . | nindent 4 }}
  {{- if gt (len $metaAnns) 0 }}
  annotations:
    {{- toYaml $metaAnns | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ include "pangolin.db.connectionSecretKey" . }}: {{ include "pangolin.db.connectionString" . | quote }}
{{- end }}
