{{- $pc := .Values.pangolin.privateConfig | default dict -}}
{{- $gen := (get $pc "generatedSecret") | default dict -}}
{{- if and (get $pc "enabled") (not (get $pc "existingSecretName")) (get $gen "create") (get $gen "data") }}
{{- $metaAnns := mergeOverwrite (dict) (include "pangolin.global.commonAnnotations" . | fromYaml) (include "pangolin.component.commonAnnotations" (dict "root" . "component" "pangolin") | fromYaml) (.Values.pangolin.secret.annotations | default dict) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pangolin.privateConfig.secretName" . }}
  namespace: {{ include "pangolin.namespace" . }}
  labels:
    {{- include "pangolin.labels" . | nindent 4 }}
    {{- include "pangolin.component.commonLabels" (dict "root" . "component" "pangolin") | nindent 4 }}
    {{- include "pangolin.renderNonSelectorLabels" (dict "labels" (.Values.pangolin.secret.labels | default dict)) | nindent 4 }}
    app.kubernetes.io/component: pangolin
  {{- if gt (len $metaAnns) 0 }}
  annotations:
    {{- toYaml $metaAnns | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ (get $gen "key") | default "privateConfig.yml" | quote }}: {{ (get $gen "data") | b64enc | quote }}
{{- end }}
