{{- if and (not .Values.pangolin.secret.existingSecretName) .Values.pangolin.secret.generated.create }}
{{- $metaAnns := mergeOverwrite (dict) (include "pangolin.global.commonAnnotations" . | fromYaml) (include "pangolin.component.commonAnnotations" (dict "root" . "component" "pangolin") | fromYaml) (.Values.pangolin.secret.annotations | default dict) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pangolin.app.secretName" . }}
  namespace: {{ include "pangolin.namespace" . }}
  labels:
    {{- include "pangolin.labels" . | nindent 4 }}
    {{- include "pangolin.component.commonLabels" (dict "root" . "component" "pangolin") | nindent 4 }}
    {{- include "pangolin.renderNonSelectorLabels" (dict "labels" (.Values.pangolin.secret.labels | default dict)) | nindent 4 }}
  {{- if gt (len $metaAnns) 0 }}
  annotations:
    {{- toYaml $metaAnns | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.pangolin.secret.generated.key }}: {{ include "pangolin.app.secretValue" . | b64enc | quote }}
{{- end }}
