{{- $bp := .Values.pangolin.blueprints | default dict -}}
{{- $bpEnabled := default false (get $bp "enabled") -}}
{{- $bpEs := default (dict) (get $bp "environmentSecret") -}}
{{- $bpEsCreate := default false (get $bpEs "create") -}}
{{- $bpExistingEs := default "" (get $bp "existingEnvironmentSecret") -}}
{{- if and $bpEnabled $bpEsCreate (not $bpExistingEs) }}
{{- $metaAnns := mergeOverwrite (dict) (include "pangolin.global.commonAnnotations" . | fromYaml) (include "pangolin.component.commonAnnotations" (dict "root" . "component" "pangolin") | fromYaml) (.Values.pangolin.secret.annotations | default dict) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pangolin.blueprints.envSecretName" . }}
  namespace: {{ include "pangolin.namespace" . }}
  labels:
    {{- include "pangolin.labels" . | nindent 4 }}
    {{- include "pangolin.component.commonLabels" (dict "root" . "component" "pangolin") | nindent 4 }}
    {{- include "pangolin.renderNonSelectorLabels" (dict "labels" (.Values.pangolin.secret.labels | default dict)) | nindent 4 }}
    app.kubernetes.io/component: pangolin
  {{- if gt (len $metaAnns) 0 }}
  annotations:
    {{- toYaml $metaAnns | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $k, $v := (get $bp "environment" | default dict) }}
  {{ $k | quote }}: {{ $v | quote }}
  {{- end }}
{{- end }}
