{{- if eq (include "pangolin.db.shouldRenderConnectionSecret" .) "true" -}}
{{- $metaAnns := include "pangolin.global.commonAnnotations" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pangolin.db.connectionSecretName" . }}
  namespace: {{ include "pangolin.namespace" . }}
  labels:
    {{- include "pangolin.labels" . | nindent 4 }}
  {{- if gt (len $metaAnns) 0 }}
  annotations:
    {{- toYaml $metaAnns | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ include "pangolin.db.connectionSecretKey" . }}: {{ include "pangolin.db.connectionString" . | quote }}
{{- end -}}
