{{- $mode := include "pangolin.db.mode" . -}}
{{- $db := default (dict) .Values.database -}}
{{- $cnpg := default (dict) (get $db "cloudnativepg") -}}
{{- $auth := default (dict) (get $cnpg "auth") -}}
{{- $generated := default (dict) (get $auth "generatedSecret") -}}
{{- if and (eq $mode "cloudnativepg") ((get $generated "create") | default false) (not (get $auth "existingSecretName")) -}}
{{- $metaAnns := include "pangolin.global.commonAnnotations" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-cnpg-app-auth" (include "pangolin.fullname" .)) (get $generated "name") }}
  namespace: {{ include "pangolin.namespace" . }}
  labels:
    {{- include "pangolin.labels" . | nindent 4 }}
  {{- if gt (len $metaAnns) 0 }}
  annotations:
    {{- toYaml $metaAnns | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ default "password" (get $generated "passwordKey") }}: {{ required "database.cloudnativepg.auth.generatedSecret.password is required when auth.generatedSecret.create=true" (get $generated "password") | quote }}
{{- end -}}
